### ISSUE TITLE
Release Alpha 1

### ISSUE THREAD

**Issue by grokys** [Perspex/Perspex#79]
- [x] #76 Implement initial XAML support
- [x] #77 ~~Use NuGet packages for Gtk/Cairo stuff~~
- [x] #78 ~~Test on Linux~~
- [x] #80 Create Perspex project templates
- [x] Write docs

**Comment by grokys** [comment]
Punting on Gtk/Cairo/Linux due to various problems
